name: Scan Dependencies UI Angular

on:
  push:
    paths:
      - "src/UIs/angular/**"
  pull_request:
    paths:
      - "src/UIs/angular/**"
  schedule:
    - cron: '0 0 * * *'

env:
  WORKING_DIRECTORY: ./src/UIs/angular/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - run: npm audit --audit-level=critical
        working-directory: ./src/UIs/angular/
