name: Scan Dependencies Modular Monolith

on:
  push:
    paths: 
      - 'src/ModularMonolith/**'
  pull_request:
    paths: 
      - 'src/ModularMonolith/**'
  schedule:
    - cron: '0 * * * *'

jobs:
  build:

    defaults: 
      run:
        working-directory: src/ModularMonolith
        
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.100

    - name: dotnet restore
      run: dotnet restore

    - name: dotnet list package --vulnerable
      run: dotnet list package --vulnerable  